config/routes.rb
SimpleCalendar::Application.routes.draw do
  resources :time_offs

  resources :work_shifts

  root :to => "home#index"
  devise_for :users, :controllers => {:registrations => "registrations"}
  resources :users
end

app/models/work_shift.rb
# == Schema Information
#
# Table name: work_shifts
#
#  id             :integer          not null, primary key
#  start_of_shift :datetime
#  end_of_shift   :datetime
#  user_id        :integer
#  created_at     :datetime
#  updated_at     :datetime
#

class WorkShift < ActiveRecord::Base
  belongs_to :user
end

app/controllers/work_shifts_controller.rb
class WorkShiftsController < ApplicationController
  before_action :set_work_shift, only: [:show, :edit, :update, :destroy]

  # GET /work_shifts
  # GET /work_shifts.json
  def index
    @work_shifts = WorkShift.all
    @work_shifts_by_date = @work_shifts.group_by{ |work_shift| work_shift.start_of_shift.to_date}
    @date = params[:date] ? Date.parse(params[:date]) : Date.today
  end

  def show
  end

  def new
    @work_shift = WorkShift.new
  end

  def edit
  end

  def create
    @work_shift = WorkShift.new(work_shift_params)

    respond_to do |format|
      if @work_shift.save
        format.html { redirect_to @work_shift, notice: 'Work shift was successfully created.' }
        format.json { render action: 'show', status: :created, location: @work_shift }
      else
        format.html { render action: 'new' }
        format.json { render json: @work_shift.errors, status: :unprocessable_entity }
      end
    end
  end

  def update
    respond_to do |format|
      if @work_shift.update(work_shift_params)
        format.html { redirect_to @work_shift, notice: 'Work shift was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: 'edit' }
        format.json { render json: @work_shift.errors, status: :unprocessable_entity }
      end
    end
  end

  def destroy
    @work_shift.destroy
    respond_to do |format|
      format.html { redirect_to work_shifts_url }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_work_shift
      @work_shift = WorkShift.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def work_shift_params
      params.require(:work_shift).permit(:start_of_shift, :end_of_shift, :user_id)
    end
end

app/helpers/work_shifts_helper.rb
module WorkShiftsHelper
end

app/views/work_shifts/_form.html.erb
<%= simple_form_for(@work_shift) do |f| %>
  <%= f.error_notification %>

  <div class="form-inputs">
    <%= f.input :start_of_shift %>
    <%= f.input :end_of_shift %>
    <%= f.association :user %>
  </div>

  <div class="form-actions">
    <%= f.button :submit %>
  </div>
<% end %>

app/views/work_shifts/edit.html.erb
<h1>Editing work_shift</h1>

<%= render 'form' %>

<%= link_to 'Show', @work_shift %> |
<%= link_to 'Back', work_shifts_path %>

app/views/work_shifts/index.html.erb
<h1>Listing work_shifts</h1>

<div id="articles">
  <h2 id="month">
    <%= link_to "<", date: @date.prev_month %>
    <%= @date.strftime("%B %Y") %>
    <%= link_to ">", date: @date.next_month %>
  </h2>
  <%= calendar @date do |date| %>
    <%= date.day %>
    <% if @work_shifts_by_date[date] %>
      <ul>
        <% @work_shifts_by_date[date].each do |work_shift| %>
          <li><%= link_to work_shift.user.name, work_shift %><br />
          <%= work_shift.start_of_shift.strftime("%H:%M") %> - <%= work_shift.end_of_shift.strftime("%H:%M") %></li>
        <% end %>
      </ul>
    <% end %>
  <% end %>
</div>

<br>

<%= link_to 'New Work shift', new_work_shift_path %>

app/views/work_shifts/new.html.erb
<h1>New work_shift</h1>

<%= render 'form' %>

<%= link_to 'Back', work_shifts_path %>

app/views/work_shifts/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Start of shift:</strong>
  <%= @work_shift.start_of_shift %>
</p>

<p>
  <strong>End of shift:</strong>
  <%= @work_shift.end_of_shift %>
</p>

<p>
  <strong>User:</strong>
  <%= @work_shift.user.name %>
</p>

<%= link_to 'Edit', edit_work_shift_path(@work_shift) %> |
<%= link_to 'Back', work_shifts_path %>