config/routes.rb
SimpleCalendar::Application.routes.draw do
  resources :time_offs

  resources :work_shifts

  root :to => "home#index"
  devise_for :users, :controllers => {:registrations => "registrations"}
  resources :users
end

app/models/time_off.rb
# == Schema Information
#
# Table name: time_offs
#
#  id         :integer          not null, primary key
#  start_date :date
#  end_date   :date
#  reason     :string(255)
#  user_id    :integer
#  created_at :datetime
#  updated_at :datetime
#

class TimeOff < ActiveRecord::Base
  belongs_to :user
end

app/controllers/time_offs_controller.rb
class TimeOffsController < ApplicationController
  before_action :set_time_off, only: [:show, :edit, :update, :destroy]

  # GET /time_offs
  # GET /time_offs.json
  def index
    @time_offs = TimeOff.all
  end

  # GET /time_offs/1
  # GET /time_offs/1.json
  def show
  end

  # GET /time_offs/new
  def new
    @time_off = TimeOff.new
  end

  # GET /time_offs/1/edit
  def edit
  end

  # POST /time_offs
  # POST /time_offs.json
  def create
    @time_off = TimeOff.new(time_off_params)

    respond_to do |format|
      if @time_off.save
        format.html { redirect_to @time_off, notice: 'Time off was successfully created.' }
        format.json { render action: 'show', status: :created, location: @time_off }
      else
        format.html { render action: 'new' }
        format.json { render json: @time_off.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /time_offs/1
  # PATCH/PUT /time_offs/1.json
  def update
    respond_to do |format|
      if @time_off.update(time_off_params)
        format.html { redirect_to @time_off, notice: 'Time off was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: 'edit' }
        format.json { render json: @time_off.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /time_offs/1
  # DELETE /time_offs/1.json
  def destroy
    @time_off.destroy
    respond_to do |format|
      format.html { redirect_to time_offs_url }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_time_off
      @time_off = TimeOff.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def time_off_params
      params.require(:time_off).permit(:start_date, :end_date, :reason, :user_id)
    end
end

app/helpers/time_offs_helper.rb
module TimeOffsHelper
end

app/views/time_offs/_form.html.erb
<%= simple_form_for(@time_off) do |f| %>
  <%= f.error_notification %>

  <div class="form-inputs">
    <%= f.input :start_date %>
    <%= f.input :end_date %>
    <%= f.input :reason %>
    <%= f.association :user %>
  </div>

  <div class="form-actions">
    <%= f.button :submit %>
  </div>
<% end %>

app/views/time_offs/edit.html.erb
<h1>Editing time_off</h1>

<%= render 'form' %>

<%= link_to 'Show', @time_off %> |
<%= link_to 'Back', time_offs_path %>

app/views/time_offs/index.html.erb
<h1>Listing time_offs</h1>

<table>
  <thead>
    <tr>
      <th>Start date</th>
      <th>End date</th>
      <th>Reason</th>
      <th>User</th>
      <th></th>
      <th></th>
      <th></th>
    </tr>
  </thead>

  <tbody>
    <% @time_offs.each do |time_off| %>
      <tr>
        <td><%= time_off.start_date %></td>
        <td><%= time_off.end_date %></td>
        <td><%= time_off.reason %></td>
        <td><%= time_off.user.name %></td>
        <td><%= link_to 'Show', time_off %></td>
        <td><%= link_to 'Edit', edit_time_off_path(time_off) %></td>
        <td><%= link_to 'Destroy', time_off, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Time off', new_time_off_path %>

app/views/time_offs/new.html.erb
<h1>New time_off</h1>

<%= render 'form' %>

<%= link_to 'Back', time_offs_path %>

app/views/time_offs/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Start date:</strong>
  <%= @time_off.start_date %>
</p>

<p>
  <strong>End date:</strong>
  <%= @time_off.end_date %>
</p>

<p>
  <strong>Reason:</strong>
  <%= @time_off.reason %>
</p>

<p>
  <strong>User:</strong>
  <%= @time_off.user.name %>
</p>

<%= link_to 'Edit', edit_time_off_path(@time_off) %> |
<%= link_to 'Back', time_offs_path %>